branch-defaults:
  master:
    environment: elixir-backend-sample-dev
    group_suffix: null
global:
  application_name: elixir_backend_sample
  branch: null
  default_ec2_keyname: null
  default_platform: Docker 18.03.1-ce
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
